#!/bin/bash -e
#
# S2I run script for the 'logstash' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/maste
